var COMMANDS  = { "en" : {
  "voice" : "UK English Female",
  "default" : 'Say "What can I say?" to see a list of commands...',
  "hi" : 'Hi, sexy!',
  "whois" : "Who are you?",
  "whatcanisay" : 'What can I say',
  "home" : 'Go home',
  "sleep" : 'Go to sleep',
  "wake" : 'Wake up',
  "debug" : 'Show debug information',
  "map" : 'Show map',
  "locaiton" : 'Show (me a) map of *location',
  "zoomin" : '(map) zoom in',
  "zoomout" : '(map) zoom out',
  "zoomvalue" : '(map) zoom (to) *value',
  "zoomreset" : '(map) reset zoom',
  "playyoutube" : 'play *term youtube',
  "ytbplaylist" : '*term playlist',
  "stopyoutube" : 'stop youtube',
  "subway" : 'show me *linenumber info at *station',
  "musicplay" : "play music",
  "musicstop" : "stop music",
  "musicprev" : "prev music",
  "musicnext" : "next music",
  "info" :  "Here is a list of commands...",
  "news" : "Show me news",
  "photo" : "Take a photo",
  "video" : "Take a video",
  "lighton" : "Light on",
  "lightoff" : "Light off"
},
  "ko" : {
    "voice" : "Korean Female",
    "default" : '"거울아거울아"를 불러주세요',
    "mirror" : "거울아 거울아 세상에서 누가 제일 이쁘니",
    "mirror_2" : "거울아 거울아 이 세상에서 누가 제일 이쁘니",
    "mirror_3" : "거울아 거울아 이세상에서 누가 제일 예쁘니",
    "mirror_4" : "거울아 거울아이 세상에서 누가 제일 예쁘니",
  	"mirror_5" : "거울아 거울아이 세상에서 누가 제일 이쁘니",
  	"mirror_6" : "거울아 거울아이 세상에서 누가 제일 이뿌니",
  	"mirror_7" : "거울아 거울아이 세상에서 누가 제일 예 쁘니",
  	"mirror_8" : "거울아 거울아이 세상에서 누가 제일 이쁜이",
  	"mirror_9" : "거울아 거울아이 세상에서 누가 제일 예쁘지",
    "hi" : '안녕',
    "whatcanisay" : '메뉴',
    "whois" : "너는 누구니",
    "home" : '홈으로',
    "sleep" : '잘자',
    "wake" : '거울아 거울아',
    "debug" : '디버그',
    "map" : '지금 어디 야',
    "locaiton" : '*location위치 보여 줘',
    "zoomin" : '지도 확대',
    "zoomout" : '지도 축소',
    "zoomvalue" : '*value상값으로지도 설정',
    "zoomreset" : '지도 리셋',
    "playyoutube" : '*term 동영상 (재생)(켜 줘)(플레이)(틀어 줘)(보여 줘)',
    "ytbplaylist" : '*term 플레이어 (재생)(켜 줘)(플레이)(틀어 줘)(보여 줘)',
    "stopyoutube" : '동영상 정지',
    "subway" : '*station역 *linenumber(호)선 *updown',
    "musicplay" : "음악 재생",
    "musicstop" : "음악 정지",
    "musicprev" : "이전",
    "musicnext" : "다음",
    "info" : "다음은 사용 가능한 질문입니다",
    "news" : "뉴스 보여 줘",
    "photo" : "사진 촬영",
    "video" : "비디오 촬영",
    "lighton" : "불 켜",
    "lightoff" : "불 꺼"
  }
};
